project:
  type: book
  output-dir: _book

book:
  title: "Open Music Europe Valuation Case Studies"
  subtitle: Validating and improving the CEEMID background, and providing inputs for the surveys carried out in WP3
  author:
     - name:
          given: "Daniel"
          family: "Antal"
          degrees: "CFA"
       orcid: 0000-0001-7513-6760
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
     - name: "Anna Márta Mester"
       orcid: 0009-0008-2274-8163
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
  date: today
  repo-url: https://github.com/dataobservatory-eu/openmuse-valuation
  repo-actions: [edit]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - glossary.qmd
    - overview.qmd
    - musiccomparators.qmd
    - personaluse.qmd
    - eventquantities.qmd
    - sustainability.qmd
    - hedonicpricemodel.qmd
    - experimentalmodels.qmd

version: 0.2.0

bibliography:
    - bib/antal.bib
    - bib/competition.bib
    - bib/datagovernance.bib
    - bib/datamodels.bib
    - bib/eulaw.bib
    - bib/ifpi.bib
    - bib/ISOdata.bib
    - bib/dataspace.bib
    - bib/musicindustry.bib
    - bib/musicreport2019.bib
    - bib/OpenMuse.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub: default
  docx:
    prefer-html: true

editor: visual

