# Glossary {.unnumbered}

## Music terms {.unnumbered}

| Term                                  | Description                                                                                                                                                                                                                                                                                                                                                                                      |
|-------------------|-----------------------------------------------------|
| `audio recording`                     | fixation of sounds \[ISRC standard\]                                                                                                                                                                                                                                                                                                                                                             |
| `author`                              | The author of music or lyrics. Entitled to authors' right or copyright.                                                                                                                                                                                                                                                                                                                          |
| `composer`                            | The author of a musical work. Entitled to authors' right or copyright.                                                                                                                                                                                                                                                                                                                           |
| `lyricist`                            | The author of the text of a musical work, or a literary text that is arranged together with a musical work. Entitled to authors' right or copyright.                                                                                                                                                                                                                                             |
| `music video recording`               | fixation of sounds synchronized with pictures or moving pictures where (a) the fixed sounds are wholly or substantially a musical performance or (b) the *recording* (3.3) is intended for viewing in association with a recording of a musical performance. \[ISRC standard\]                                                                                                                   |
| `DSP` or `digital streaming platform` | Digital service providers (DSPs), or Digital Streaming Platforms are companies or organisations that provide access to services online. DSPs can provide access to music downloads, like Apple's iTunes Store, or access to streaming music like Spotify, or even provide satellite-delivered content such as SiriusXM in the USA.                                                               |
| `performer`                           | The performer of a musical work; in case of a sound recording, the performer whose performance is fixed in the recording. They may be entitled to neighbouring or sound recording copyrights.                                                                                                                                                                                                    |
| `producer`                            | The person or legal entity that produces the recorded fixation of the sound recording. They are entitled to neighbouring or sound recording copyrights.                                                                                                                                                                                                                                          |
| `rights management (organisations)`   | the function of managing the rights on behalf of rights owners. It can be companies whose sole purpose is to ensure that content that has been licensed has delivered royalties that are identified and accounted for. The role can be taken by collective management organisations or by private companies on behalf of songwriters, composers, performers, music publishers, or record labels. |
|                                       |                                                                                                                                                                                                                                                                                                                                                                                                  |

: Music terms and definitions {tbl-colwidths="\[25,75\]"}

## Data science terms {.unnumbered}

| Term                         | Description                                                                                                                                                                                                                                                                                                                                                           |
|-------------------|-----------------------------------------------------|
| `conceptualisation`          | an abstract, simplified view of some selected part of the world, containing the objects, concepts, and other entities that are presumed of interest for some particular purpose and the relationships between them                                                                                                                                                    |
| `data`                       | reinterpretable representation of information in a formalized manner suitable for communication, interpretation, or processing Note 1 to entry: Data can be processed by humans or by automatic means.\[SOURCE:ISO/IEC 2382:2015, 2121272\]                                                                                                                           |
| `database`                   | collection of `data` organized according to a conceptual structure describing the characteristics of these data and the relationships among their corresponding entities, supporting one or more application areas. \[SOURCE:ISO/IEC 2382:2015, 2121413\]                                                                                                             |
| `data set` or `dataset`      | identifiable collection of `data` available for access or download in one or more formats \[SOURCE:Adapted from ISO 19115-2:2009, 4.7\] *Beware: various conceptual and information models use different dataset definitionns*.                                                                                                                                       |
| `register`                   | an official list or record of names or items; it aims to be a complete list of the objects in a specific group of objects or population, for example, all copyright-protected musical works in a country, or all legal person enterprises in another country.                                                                                                         |
| `data flow definition`       | a structure which describes, categorises and constrains the allowable content of a data set that providers will supply for different reference periods. \[SDMX 3.0\]                                                                                                                                                                                                  |
| `datacube`                   | A statistical data set created in a multi-dimensional space (e.g., time, geography, gender), or hyper-cube, indexed by those dimensions. *The term cube shouldn't be taken literally, it is not meant to imply that there are exactly three dimensions.*                                                                                                              |
| `knowledge base` or `K-base` | database that contains inference rules and information about human experience and expertise in a domain. 1: In self-improving systems, the knowledge base additionally contains information resulting from the solution of previously encountered problems. The terms `knowledge base` and `K-base` are standardized by ISO/IEC \[ISO/IEC 2382-1:1993\].              |
| `knowledge representation`   | process or result of encoding and storing knowledge in a knowledge base. Term and definition standardized by ISO/IEC \[ISO/IEC 2382-28:1995\].                                                                                                                                                                                                                        |
| `knowledge graph`            | a `knowledge representation` that uses a graph-structured data model to represent and operate on data.                                                                                                                                                                                                                                                                |
| `knowledge source`           | source of information from which a knowledge base has been created for a specific kind of problem Term and definition standardized by ISO/IEC \[ISO/IEC 2382-28:1995\].                                                                                                                                                                                               |
| `knowledge engineering tool` | functional tool designed to facilitate the rapid development of knowledge-based systems. 1. A knowledge engineering tool incorporates specific strategies for knowledge representation, inference, and control, as well as elementary modeling constructs for easy handling of typical problems.Term and definition standardized by ISO/IEC \[ISO/IEC 2382-28:1995\]. |
| `conceptual model`           | representation of the characteristics of a universe of discourse by means of entities and entity relationships (ISO/IEC 2382-17:1999). *In this document, we use conceptual models for models that can be used by humans and computers, too, and we use the information model term for use in IT systems.*                                                            |
| `interoperability`           | Ability of two or more systems or applications to exchange information and to mutually use the information that has been exchanged. \[SOURCE:ISO/IEC 19941:2017\]   |
| `data portability`           | Ability to easily transfer data from one system to another without being required to re-enter data.     |
| `metadata`                   | data that define and describe other data \[ISO/IEC 11179-1:2023\]; we use the more functional definition "a statement about a potentially informative object."    |
| `NERD`                       | Named-entity recognition and disambiguation    |
| `persistent identifier`      | A persistent identifier (or *permanent Identifier* or *handle*), is one that never changes, so that your bookmarks and links don't break when a website or a database or an API service gets updated.    |
| `Wikibase`                   | Wikibase is a software system that help the collaborative management of knowledge in a central repository. It was originally developed for the management of Wikidata, but it is available now for the creation of private, or public-private partnership knowledge graphs. It is developed by Wikimedia Deutschland.                                                 |

: Data and information science terms, definitions {tbl-colwidths="\[25,75\]"}

| Term            | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|------------------|------------------------------------------------------|
| `quantity`       |                                                       |
| `blanket license`|                                                       |
| `quantity estimation` |                                                 |
| `pricing      ` |                                                       |
| `price`         |                                                       |
| `historical price`  |                                                   |
| `market price`  |                                                       |
| `shadow price`  |                                                       |
| `royalty rate`  |                                                       |
| `tariff table`  |                                                       |
| `hedonic price method`|                                                 |
| `revenue`       |                                                       |
| `licensing fee` |                                                       |
| `net sales`     |                                                       |
| `valuation`     |                                                       |
| `economic value`|                                                       |
| `value in use`  |                                                       |
| `external value`|                                                       |
| `discount rate` |                                                       |
| `future revenue` |                                                      |
| `present value of future revenues` |                                    |
: Economics terms and definitions {tbl-colwidths="\[25,75\]"}

## Abbreviations

| Term         | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|------------------|------------------------------------------------------|
| `AEPO-ARTIS` | Organisation representing European artists-performers. Regroups most of the European CMO representing performers.                                                                                                                                                                                                                                                                                                                                                        |
| `CISAC`      | The International Confederation of Societies of Authors and Composers is an international non-governmental, not-for-profit organisation that aims to protect the rights and promote the interests of creators worldwide.                                                                                                                                                                                                                                                 |
| `CSRD`       | The Corporate Sustainability Reporting Directive (CSRD) is European Union (EU) legislation, effective from 5 January 2023, that requires EU businesses—including qualifying EU subsidiaries of non-EU companies—to disclose their environmental and social impacts, and how their environmental, social and governance (ESG) actions affect their business.                                                                                                              |
| `DOI`        | A [DOI (Digital Object Identifier)](https://www.doi.org/faq.html) is a standardised unique number given to many (but not all) articles, papers, & books, by some publishers, to identify a particular publication.                                                                                                                                                                                                                                                       |
| `DDI`        | The `Data Documentation Initiative` is originating for the world of social sciences data archives and more and more in use in statistical organisations for the documentation of microdata.                                                                                                                                                                                                                                                                              |
| `DSP`        | Digital service providers (DSPs), or Digital Streaming Platforms are companies or organisations that provide access to services online.                                                                                                                                                                                                                                                                                                                                  |
| `ECCCH`       | The European Collaborative Cloud for Cultural Heritage is a European Union initiative for a digital infrastructure that will connect cultural heritage institutions and professionals across the EU.                                                                                                                                                                                                                                                                                       |
| `EFRAG`      | The European Financial Reporting Advisory Group is a private association established in 2001 with the encouragement of the European Commission to serve the public interest. EFRAG extended its mission in 2022 following the new role assigned to EFRAG in the CSRD, providing Technical Advice to the European Commission in the form of fully prepared draft EU Sustainability Reporting Standards and/or draft amendments to these Standards.                        |
| `EMO`        | The European Music Observatory (EMO) is envisioned as a hub for collecting and analyzing data on the music sector across Europe. Its primary aim is to address the current gaps and inconsistencies in music data collection, which have been a significant challenge for the sector.                                                                                                                                                                                    |
| `ESRS`       | The European Sustainability Reporting Standards (ESRS) are a set of guidelines developed by the European Financial Reporting Advisory Group (EFRAG) to standardise sustainability reporting across the European Union. These standards are designed to align with the Corporate Sustainability Reporting Directive (CSRD), which mandates detailed corporate reporting on environmental, social, and governance (ESG) issues for many companies operating within the EU​m |
| `GESAC`      | GESAC comprises together 32 European authors' societies in music, audiovisual, visual arts, literature and drama.                                                                                                                                                                                                                                                                                                                                                        |
| `GSBPM`      | The `Generic Statistical Business Process Model` is a international standard model that “describes and defines the set of business processes needed to produce official statistics.”                                                                                                                                                                                                                                                                                     |
| `GSIM`       | `Generic Statistical Information Model`: a common abstract representation of data objects manipulated in official statistical production and elaborated as an overarching model for implementation standards such as SDMX or DDI.                                                                                                                                                                                                                                        |
| `ICMP`       | ICMP is the global trade body representing the music publishing industry worldwide.                                                                                                                                                                                                                                                                                                                                                                                      |

| `ISNI`       | the ISO certified global standard number for identifying the millions of contributors to creative works and those active in their distribution.                                                                                                                                                                                                                                                                                                                          |
| `ISMN`       | The `International Standard Music Number` identifies published music sheets.                                                                                                                                                                                                                                                                                                                                                                                             |
| `ISRC`       | The International Standard Recording Code (ISRC) is the international identification system for sound recordings and music video recordings. It was codified in the ISO 3901 standard in 1986.                                                                                                                                                                                                                                                                           |
| `ISWC`       | International Standard Musical Work Code is a unique identifier for musical works. It is adopted as international standard ISO 15707.                                                                                                                                                                                                                                                                                                                                    |
| `PPP`        | A Public-Private Partnership (PPP) is a collaborative arrangement between government entities and private sector companies aimed at financing, designing, implementing, and operating projects or services traditionally provided by the public sector.                                                                                                                                                                                                                  |
| `SCAPR`      | International association for the development of the practical cooperation between performers’ collective management organisations (CMOs)                                                                                                                                                                                                                                                                                                                                |
| `SDMX`       | Statistical Data and Metadata eXchange (SDMX), is an international initiative that aims at standardising and modernising ("industrialising") the mechanisms and processes for the exchange of statistical data and metadata among international organisations and their member countries.                                                                                                                                                                                |
| `URI`        | A Uniform Resource Identifier (URI) is a string of characters used to identify a resource on the internet. This resource can be either abstract or physical, such as a website, an email address, or a file. URIs are essential for enabling interactions with resources over a network using specific protocols.                                                                                                                                                        |
| `VIAF`       | The Virtual International Authority File (VIAF) is an international service that consolidates multiple name authority files into a single database. Their primary goal is to enhance the efficiency and usability of library authority files by linking and merging widely used authority records and making them accessible online.                                                                                                                                     |

: Abbreviations of terms {tbl-colwidths="\[25,75\]"}

Our glossary is harmonised with relevant music-sector specific standards (referred to in @sec-standardisation) and with the ISO *Information technology — Vocabulary* [@iso_2382_2015]; *Information technology — Cloud computing — Taxonomy based data handling for cloud services* [@iso_22624_2020] and *Information technology — Cloud computing — Interoperability and portability* [@iso_19941_2017]. {{< pagebreak >}}
